# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Porfolios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name=100)),
                ('txn_date', models.DateField()),
                ('porfolio_name', models.CharField(max_length=200)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioX.Investor')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='porfolios',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioX.Security'),
        ),
    ]
